sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            - position: right
              type: sonata.block.service.text
              settings:
                  content: >
                      <h2>Welcome to the Sonata Admin</h2>
                      <p>This is a <code>sonata.block.service.text</code> from the Block
                      Bundle, you can create and add new block in these area by configuring
                      the <code>sonata_admin</code> section.</p> <br/> For instance, here
                      a RSS feed parser (<code>sonata.block.service.rss</code>):
            - position: right
              type: sonata.block.service.rss
              roles: [ POST_READER ]
              settings:
                  title: Sonata Project's Feeds
                  url: https://sonata-project.org/blog/archive.rss
        groups:
            app.admin.group.content:
                label: content
                label_catalogue: App
                items:
                    - app.admin.list

#            app.admin.group.blog:
#                items:
#                    - app.admin.list
#                item_adds:
#                    - sonata.admin.page
#                roles: [ 'ROLE_ONE', 'ROLE_TWO' ]

    templates:
        # default global templates
        layout: '@SonataAdmin/standard_layout.html.twig'
        ajax: '@SonataAdmin/ajax_layout.html.twig'

        # default value if done set, actions templates, should extend global templates
        list: '@SonataAdmin/CRUD/list.html.twig'
        show: '@SonataAdmin/CRUD/show.html.twig'
        edit: '@SonataAdmin/CRUD/edit.html.twig'
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'


    security:

        # the default value
#        handler: sonata.admin.security.handler.role

        # use this service if you want ACL
#        handler: sonata.admin.security.handler.acl

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
